FORMAT: 1A
HOST: http://localhost:8080/demo/

# demo_spring_api

API for test task. Spring boot is used for creation.
Author: Yernur Alimkhanov

## Request Categories [/categories]

### List All Categories [GET]

+ Response 200 (application/json)
    [
  {
    "id": 7,
    "name": "Унитазы",
    "childCategories": []
  },
  {
    "id": 2,
    "name": "Мебель",
    "childCategories": [
      {
        "id": 5,
        "name": "Кухня,Ванная",
        "childCategories": [
          {
            "id": 9,
            "name": "Мебель_для_ванной",
            "childCategories": []
          }
        ]
      }
    ]
  },
  {
    "id": 3,
    "name": "Сантехника",
    "childCategories": [
      {
        "id": 6,
        "name": "Ванны",
        "childCategories": []
      },
      {
        "id": 7,
        "name": "Унитазы",
        "childCategories": []
      }
    ]
  },
  {
    "id": 4,
    "name": "Электрика",
    "childCategories": [
      {
        "id": 8,
        "name": "Розетки",
        "childCategories": []
      }
    ]
  },
  {
    "id": 6,
    "name": "Ванны",
    "childCategories": []
  },
  {
    "id": 8,
    "name": "Розетки",
    "childCategories": []
  },
  {
    "id": 1,
    "name": "Стройтельство_и_ремонт",
    "childCategories": [
      {
        "id": 3,
        "name": "Сантехника",
        "childCategories": [
          {
            "id": 6,
            "name": "Ванны",
            "childCategories": []
          },
          {
            "id": 7,
            "name": "Унитазы",
            "childCategories": []
          }
        ]
      },
      {
        "id": 4,
        "name": "Электрика",
        "childCategories": [
          {
            "id": 8,
            "name": "Розетки",
            "childCategories": []
          }
        ]
      }
    ]
  },
  {
    "id": 5,
    "name": "Кухня,Ванная",
    "childCategories": [
      {
        "id": 9,
        "name": "Мебель_для_ванной",
        "childCategories": []
      }
    ]
  },
  {
    "id": 9,
    "name": "Мебель_для_ванной",
    "childCategories": []
  }
]

## Request Product [/category/7]
This section of API returns all products from particular category. 
URL pattern of this request "/category/{id}".

### List Products of Category [GET]

+ Response 200 (application/json)
[
  {
    "id": 3,
    "name": "Компакт JUST 031",
    "price": 28913,
    "brand": "Cersanit",
    "features": [
      {
        "id": 9,
        "name": "Материал",
        "value": "Фарфор"
      },
      {
        "id": 8,
        "name": "Тип",
        "value": "Инсталляции"
      },
      {
        "id": 7,
        "name": "Тип_переключения",
        "value": "двухрежимный"
      }
    ]
  },
  {
    "id": 4,
    "name": "Solido 4 в 1",
    "price": 165000,
    "brand": "GROHE",
    "features": [
      {
        "id": 12,
        "name": "Материал",
        "value": "Дюропласт"
      },
      {
        "id": 10,
        "name": "Тип_переключения",
        "value": "двухрежимный"
      },
      {
        "id": 11,
        "name": "Тип",
        "value": "Подвесные_унитазы"
      }
    ]
  }
]

## Request Filters [/category/filters/7]
This section of API returns all filters from particular category. 
URL pattern of this request "/category/filters/{id}".

### List Filters of Category [GET]

+ Response 200 (application/json)
[
  {
    "id": 6,
    "name": "Материал",
    "features": [
      {
        "id": 12,
        "name": "Материал",
        "value": "Дюропласт"
      },
      {
        "id": 9,
        "name": "Материал",
        "value": "Фарфор"
      }
    ]
  },
  {
    "id": 4,
    "name": "Тип_переключения",
    "features": [
      {
        "id": 10,
        "name": "Тип_переключения",
        "value": "двухрежимный"
      },
      {
        "id": 7,
        "name": "Тип_переключения",
        "value": "двухрежимный"
      }
    ]
  },
  {
    "id": 5,
    "name": "Тип",
    "features": [
      {
        "id": 11,
        "name": "Тип",
        "value": "Подвесные_унитазы"
      },
      {
        "id": 8,
        "name": "Тип",
        "value": "Инсталляции"
      }
    ]
  }
]

## Request Product with Filters [/category/7/6=Фарфор&5=Инсталляции]
This section of API returns all products from particular category with choosen filters. 
URL pattern of this request "/category/{id}/{filter}".

### List Products of Category with Filter on [GET]

+ Response 200 (application/json)
[
  {
    "id": 3,
    "name": "Компакт JUST 031",
    "price": 28913,
    "brand": "Cersanit",
    "features": [
      {
        "id": 7,
        "name": "Тип_переключения",
        "value": "двухрежимный"
      },
      {
        "id": 9,
        "name": "Материал",
        "value": "Фарфор"
      },
      {
        "id": 8,
        "name": "Тип",
        "value": "Инсталляции"
      }
    ]
  }
]